-- Database Initialisation
-- User
INSERT INTO user_table(last_name, first_name, email, password, creation_date, modification_date, email_verified) VALUES
('Durand', 'Alice', 'alice.durand@example.com', '$2y$10$eqjReaDGnKGfJbGHGib7te.mCZoaLDmcby8GYw1jlIpVoLZykM4kq', '2025-08-01T10:00:00', '2025-08-01T10:00:00', true),
('Martin', 'Bob', 'bob.martin@example.com', '$2y$10$eqjReaDGnKGfJbGHGib7te.mCZoaLDmcby8GYw1jlIpVoLZykM4kq', '2025-08-01T11:00:00', '2025-08-01T11:00:00', false),
('Lemoine', 'Claire', 'claire.lemoine@example.com', '$2y$10$eqjReaDGnKGfJbGHGib7te.mCZoaLDmcby8GYw1jlIpVoLZykM4kq', '2025-08-01T12:00:00', '2025-08-01T12:00:00', true);

--Tag
INSERT INTO tag_table(name) VALUES
-- Organisation / Travail
('Travail'),
('Personnel'),
('Urgent'),
('Important'),
('À faire'),
('Projet'),
('Idée'),
('Note'),
('Résumé'),
('Réunion'),
('Appel'),
('Tâche'),
('Planification'),
('Objectif'),
('Agenda'),
('Événement'),
('Rappel'),
('Checklist'),
('Priorité'),
-- Etudes / Académique
('Cours magistral'),
('Travaux dirigés'),
('Travaux pratiques'),
('Mémoire'),
('Thèse'),
('Examen'),
('Recherche'),
('Lecture académique'),
('Synthèse'),
('Rapport'),
('Présentation'),
('Projet académique'),
('Étude de cas'),
('Statistiques'),
('Analyse'),
('Expérimentation'),
('Observation'),
('Révision'),
('Apprentissage'),
('Tutoriel'),
('Exercice'),
-- Sciences
('Mathématiques'),
('Physique'),
('Chimie'),
('Biologie'),
('Médecine'),
('Informatique'),
('Astronomie'),
('Géologie'),
('Écologie'),
('Océanographie'),
('Psychologie'),
('Sociologie'),
('Anthropologie'),
('Histoire'),
('Géographie'),
('Économie'),
('Politique'),
('Droit'),
('Linguistique'),
('Neurosciences'),
-- Technologie / Informatique
('Programmation'),
('Développement Web'),
('Développement Mobile'),
('Base de données'),
('Réseaux'),
('Algorithmique'),
('Intelligence Artificielle'),
('Machine Learning'),
('Deep Learning'),
('Data Science'),
('Big Data'),
('Cybersécurité'),
('Blockchain'),
('Cryptographie'),
('Cloud'),
('DevOps'),
('Tests logiciels'),
('UX/UI'),
('Robotique'),
('IoT'),
('Automatisation'),
-- Arts / Créativité / Loisirs
('Musique'),
('Chant'),
('Instrument'),
('Peinture'),
('Dessin'),
('Sculpture'),
('Photographie'),
('Vidéo'),
('Cinéma'),
('Écriture'),
('Théâtre'),
('Danse'),
('Design'),
('Mode'),
('Architecture'),
('Jeux vidéo'),
('Jeux de société'),
('DIY'),
('Cuisine'),
('Voyage'),
('Sport'),
('Fitness'),
('Yoga'),
('Méditation'),
('Bien-être'),
('Lecture loisir'),
('Podcast'),
('Blog'),
-- Vie quotidienne / Pratique
('Finances'),
('Budget'),
('Facture'),
('Banque'),
('Assurance'),
('Santé'),
('Alimentation'),
('Courses'),
('Maison'),
('Jardinage'),
('Animaux'),
('Transport'),
('Voiture'),
('Immobilier'),
('Administration'),
('Contrat'),
('Démarches'),
('Logement'),
('Énergie'),
-- Communication / Social
('Email'),
('Message'),
('Discussion'),
('Réseaux sociaux'),
('Collaboration'),
('Client'),
('Fournisseur'),
('Partenaire'),
('Feedback'),
('Networking'),
('Pitch'),
('Compte rendu'),
('Présentation pro'),
-- Développement personnel
('Motivation'),
('Objectif personnel'),
('Habitude'),
('Journal'),
('Réflexion'),
('Compétence'),
('Apprentissage continu'),
('Plan d’action'),
('Mindset'),
('Productivité'),
('Organisation'),
-- Culture / Histoire / Littérature
('Art'),
('Histoire de l’art'),
('Littérature'),
('Roman'),
('Essai'),
('Biographie'),
('Poésie'),
('Manifestes'),
('Théorie artistique'),
('Culture'),
('Patrimoine'),
('Religion'),
('Mythologie'),
('Philosophie'),
-- Divers
('Inspiration'),
('Innovation'),
('Recherche avancée'),
('Inclassable'),
('Divers'),
('Archive'),
('Projet futur'),
('Idée créative')